### ISSUE TITLE
Custom trackers

### ISSUE THREAD

**Issue by maxence-cote** [frankrousseau/kyou#1] opened 2013-08-26 10:43 UTC
Hi Frank,

Great work on Kyou, definitely a tool I'm looking forward, very useful! It occurred to me there is plenty of things we might want to track, custom trackers would be perfect for that.
- There is things we want to track only temporally, say if I'm sick maybe I want to monitor when i take my medication or how many time i blow my noose.
- There is things we want to monitor constantly, say my cigarette consumption.

How I see this, we would need to be able to add a tracker where:
- we choose the label
- and the counter type (+1 or number, or string/tagg), 
- ideally we would be able to track more than one thing per chart (say medicine + coughing).
- Finally, a counter could be active or inactive, when I have healed I don't want to see on my "dashboard" the counter anymore, but I may want to activate it again the next time I fall sick. 

Cheers.

**Comment by frankrousseau** [comment] 2016-02-20 21:27
I think most of the points of this issue are fixed and the issue is quite old now. So, I prefer to close it.

Thank you both for reporting.

**Closed by frankrousseau** 2016-02-20 21:27 UTC
